# --- Portfolio settings and configurations ---

title: Harrison Turley
description: >-
  A portfolio of past projects and achievements by Harrison Turley.
baseurl: ''
url: 'https://harrisonturley.github.io'
github_username:  harrisonturley

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass

# Information and settings
name:                 "Harrison Turley"
avatar:               "true"
email:                "harrison.turley.1998@gmail.com"
personal_title:       "3rd Year Computer Engineering Student"
summary:              "I am currently studying Computer Engineering at the University of British Columbia.  I have experience in the technology industry both as a Software Engineer and a Quality Assurance tester.  I have a passion for learning new technologies and building software that can positively impact people's lives.  If you want to say hi, please feel free to contact me using the details below!"

experience_toggle:    true
education_toggle:     true
projects_toggle:      true
hackathons_toggle:    true
skills_toggle:        true
links_toggle:         true

social_links:
  github_url:         "https://github.com/harrisonturley"
  linkedin_url:       "https://www.linkedin.com/in/harrison-turley-973636124/"
print_social_links:   true
