# --- Portfolio settings and configurations ---

title: Harrison Turley
description: >-
  A portfolio of past projects and achievements by Harrison Turley.
baseurl: ""
url: ""
github_username:  harrisonturley

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed

name:                 "Harrison Turley"
avatar:               "true"
email:                "harrrison.turley.1998@gmail.com"
personal_title:       "3rd Year Computer Engineering Student"
summary:              "I am currently studying Computer Engineering at the University of British Columbia, Vancouver campus.  My expected graduation date is May 2021.  I have experience in the technology industry both as a Quality Assurance tester and a Software Engineer, and I hope to continue with developing software for the future."

experience_toggle:    true
education_toggle:     true
projects_toggle:      true
skills_toggle:        true
recognition_toggle:   true
links_toggle:         true
associations_toggle:  true

social_links:
  github_url:         "https://github.com/harrisonturley"
  linkedin_url:       "https://www.linkedin.com/in/harrison-turley-973636124/"
print_social_links:   true
