# --- Portfolio settings and configurations ---

title: Harrison Turley
description: >-
  A portfolio of past projects and achievements by Harrison Turley.
baseurl: ''
url: 'https://harrisonturley.github.io'
github_username:  harrisonturley

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass

# Information and settings
name:                 "Harrison Turley"
avatar:               "true"
email:                "harrison.turley.1998@gmail.com"
personal_title:       "3rd Year Computer Engineering Student"
summary:              "I am a software engineer and self-professed tech geek! I find that there's nothing better than stepping back and seeing the final product of a development phase come together. I love problem solving and the excitement that comes from fixing that one bug that has been plaguing the project, or making a breakthrough on implementing a new feature.<br/><br/>From my past projects and work, I have found that I most enjoy working on user-level applications. Desktop or mobile; front end, back end, or full stack, I enjoy all kinds of user-level application development.<br/><br/>I am a huge fan of coding collaboratively and working out loud. I love hearing about the challenges that my teammates are tackling and seeing where I can help them.<br/><br/>If you would like to chat, I am always interested in talking to new people with shared interests! "

experience_toggle:    true
education_toggle:     true
projects_toggle:      true
hackathons_toggle:    true
skills_toggle:        true
links_toggle:         true

social_links:
  github_url:         "https://github.com/harrisonturley"
  linkedin_url:       "https://www.linkedin.com/in/harrison-turley-973636124/"
print_social_links:   true
